version: "3"
services:
  airspace-backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - database:database
    networks:
      - backend
  database:
    image: "postgres:12.2"
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_USER=steven
      - POSTGRES_PASSWORD=gabagool
      - POSTGRES_DB=airspace
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
      - backend
volumes:
  database-data: # named volumes can be managed easier using docker-compose

networks:
  backend:
